package com.akaita.fda.database;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * Created by mikel on 18/05/2015.
 */
@DatabaseTable(tableName = "album")
public class Album {
    // we use this field-name so we can query for posts with a certain id
    public final static String ID_FIELD_NAME = "id";
    public static final String TYPE_ID_FIELD_NAME = "type_id";

    // this id is generated by the database and set on the object when it is passed to the create method
    @DatabaseField(id = true, columnName = ID_FIELD_NAME)
    long id;

    @DatabaseField
    String title;

    @DatabaseField
    String pictureUrl;

    @DatabaseField(foreign = true, foreignAutoRefresh = true, columnName = TYPE_ID_FIELD_NAME)
    Type type;

    Album() {
        // for ormlite
    }

    public Album(long id, String title, Type type, String pictureUrl) {
        this.id = id;
        this.title = title;
        this.type = type;
        this.pictureUrl = pictureUrl;
    }
}
